server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: false
  application:
    name: apigateway